name: unittest_pytest_coverage_doc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  pep8_check:
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies for PEP 8 code style check (ubuntu packages)
      run: sudo apt install pep8
    - name: check PEP 8 code style
      run: pep8 --show-source --show-pep8 --statistics $(find -name "*.py")

  ubuntu_test_doc:
    needs: pep8_check
    strategy:
      matrix:
        # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md
        # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
        # we could also use: ubuntu-latest
        os: [ubuntu-18.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies (ubuntu packages)
      run: sudo apt install python3-setuptools hashdeep
    - name: check all modules available
      run: env python3 setup.py check_modules
    - name: install pfu
      run: sudo python3 setup.py install
    - name: run pfu
      run: |
        which pfu
        pfu -h
    - name: unittest
      run: env python3 setup.py run_unittest
    - name: install dependencies for pytest (ubuntu packages)
      run: sudo apt install python3-pytest python3-pytest-cov python3-pytest-xdist
    - name: pytest
      run: env python3 setup.py run_pytest --parallel --coverage

  macos-1015_test:
    needs: pep8_check
    # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: check all modules available
      run: env python3 setup.py check_modules
    - name: install pfu
      run: sudo python3 setup.py install
    - name: run pfu
      run: |
        which pfu
        pfu -h
    - name: unittest
      run: env python3 setup.py run_unittest
    - name: install dependencies via pip3
      run: pip3 install wheel pytest pytest-cov pytest-xdist
    - name: pytest
      run: env python3 setup.py run_pytest --parallel --coverage

  windows_test:
    needs: pep8_check
    strategy:
      matrix:
        # we need setuputils to create binaries for windows
        # https://github.com/actions/virtual-environments/blob/main/images/win/Windows2016-Readme.md
        # https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
        os: [windows-2016, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: conda init powershell
      run: |
        &($env:CONDA + "\Scripts\conda") init powershell
    - name: install dependencies via conda
      run: conda install -c conda-forge python pytest pytest-cov pytest-xdist
    - name: check all modules available
      run: python setup.py check_modules
    - name: install pfu
      run: python setup.py install
    - name: run pfu
      run: |
        Get-Command pfu
        pfu -h
    - name: unittest
      run: python setup.py run_unittest
    - name: pytest
      run: python setup.py run_pytest --parallel --coverage
