name: unittest_pytest_coverage_doc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  ubuntu-1804_test_doc:
    # if: ${{ false }}
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies (ubuntu packages)
      run: sudo apt install python3-setuptools
    - name: check all modules available
      run: env python3 setup.py check_modules
    - name: install pfu
      run: sudo python3 setup.py install
    - name: run pfu
      run: |
        which pfu
        pfu -h
    - name: unittest
      run: env python3 setup.py run_unittest
    - name: install dependencies for pytest (ubuntu packages)
      run: sudo apt install python3-pytest python3-pytest-cov python3-pytest-xdist
    - name: pytest
      run: env python3 setup.py run_pytest --parallel --coverage

  ubuntu-2004_test_doc:
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
#    runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies (ubuntu packages)
      run: sudo apt install python3-setuptools
    - name: check all modules available
      run: env python3 setup.py check_modules
    - name: install pfu
      run: sudo python3 setup.py install
    - name: run pfu
      run: |
        which pfu
        pfu -h
    - name: unittest
      run: env python3 setup.py run_unittest
    - name: install dependencies for pytest (ubuntu packages)
      run: sudo apt install python3-pytest python3-pytest-cov python3-pytest-xdist
    - name: pytest
      run: env python3 setup.py run_pytest --parallel --coverage

  macos-1015_test:
    # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: check all modules available
      run: env python3 setup.py check_modules
    - name: install pfu
      run: sudo python3 setup.py install
    - name: run pfu
      run: |
        which pfu
        pfu -h
    - name: foo bar
      run: |
        mkdir foo
        pfu simscrub -config_data_directory foo
        pfu simscrub
        pfu simscrub -dir .
        pfu simscrub
    - name: unittest
      run: env python3 setup.py run_unittest
    - name: install dependencies via pip3
      run: pip3 install wheel pytest pytest-cov pytest-xdist
    - name: pytest
      run: env python3 setup.py run_pytest --parallel --coverage

  windows-2016_test:
    # we need setuputils to create binaries for windows
    # https://github.com/actions/virtual-environments/blob/main/images/win/Windows2016-Readme.md
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@v2
    - name: conda init powershell
      run: |
        &($env:CONDA + "\Scripts\conda") init powershell
    - name: install dependencies via conda
      run: conda install -c conda-forge python pytest pytest-cov pytest-xdist
    - name: check all modules available
      run: python setup.py check_modules
    - name: install pfu
      run: python setup.py install
    - name: run pfu
      run: |
        Get-Command pfu.py
        pfu.py -h
    - name: Get-Command pfu
      run: Get-Command pfu.py
    - name: run pfu
      run: pfu.py -h
    - name: foo1
      run: mkdir foo
    - name: foo2
      run: pfu.py simscrub -config_data_directory foo
    - name: foo3
      run: pfu.py simscrub
    - name: foo4
      run: pfu.py simscrub -dir .
    - name: foo5
      run: pfu.py simscrub
    - name: unittest
      run: python setup.py run_unittest
    - name: pytest
      run: python setup.py run_pytest --parallel --coverage

  windows-2019_test:
    if: ${{ false }}
    # https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: conda init powershell
      run: |
        &($env:CONDA + "\Scripts\conda") init powershell
    - name: install dependencies via conda
      run: conda install -c conda-forge python pytest pytest-cov pytest-xdist
    - name: check all modules available
      run: python setup.py check_modules
    - name: install pfu
      run: python setup.py install
    - name: run pfu
      run: |
        Get-Command pfu.py
        pfu.py -h
    - name: foo bar
      run: |
        mkdir foo
        pfu.py simscrub -config_data_directory foo
        pfu.py simscrub
        pfu.py simscrub -dir .
        pfu.py simscrub
    - name: unittest
      run: python setup.py run_unittest
    - name: pytest
      run: python setup.py run_pytest --parallel --coverage
